export const ACTIONS_STATUS_EVENT_EMITTER = 'ACTIONS_STATUS_EVENT_EMITTER';
export const DEFAULT_DATE_FORMAT = 'YYYY/MM/DD';
export const DEFAULT_DAY_HOURS_RANGE_START = 9;
export const DEFAULT_DAY_HOURS_RANGE_END = 18;
export const DEFAULT_TIME_IN_ONE_BLOCK = 5;
